import { Link } from 'react-router-dom';

function PrivacyPage() {
  return (
    <div className="page-content fade-in" style={{ maxWidth: '720px', margin: '0 auto' }}>
      <Link to="/" className="button-back">&larr; Back to nullcomma.com</Link>

      <div className="glass-content-card">
        <h1 style={{ color: 'var(--color-light)', fontSize: '2rem', marginBottom: '0.5rem' }}>Privacy Policy</h1>
        <p style={{ color: 'var(--color-grey)', marginBottom: '1.5rem' }}>This policy applies to all Null Comma products: this website, games, tools, applications, and any services or integrations provided under the Null Comma brand.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Scope</h2>
        <p>This Privacy Policy covers all digital products and services created and distributed by Null Comma, including but not limited to: the nullcomma.com website, downloadable games and prototypes, the Null Comma Launcher, web applications, browser extensions, and any future tools or applications released under this brand.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Data Collection</h2>
        <p>Null Comma products do not collect, store, or share any personal data. No cookies, no tracking scripts, no analytics services, no telemetry, and no crash reporting are used in any of our products.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Website</h2>
        <p>The nullcomma.com website does not use cookies, tracking scripts, analytics services, or OAuth logins. No personal data is collected through browsing or interacting with the site. The contact form sends your message through <a href="https://formspree.io">Formspree</a>, which processes it privately. I do not retain, sell, or access your submitted data beyond responding to your message.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Games and Applications</h2>
        <p>All games, tools, and applications created by Null Comma run locally on your device. They do not transmit any data to external servers, do not require an internet connection to function, and do not collect telemetry, usage statistics, or crash reports. Any data generated by these products (such as save files, preferences, or configuration) is stored exclusively on your local device.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Third-Party Services and Integrations</h2>
        <p>Some Null Comma products may interact with third-party services:</p>
        <p><strong>Steam:</strong> Games distributed on Steam may use the Steamworks SDK for features such as achievements, cloud saves, and leaderboards. These features are governed by Valve's privacy policy. Null Comma does not access or store any Steam user data.</p>
        <p><strong>YouTube:</strong> This website embeds video trailers from YouTube. YouTube has its own privacy policy. This site is not affiliated with YouTube or Google.</p>
        <p><strong>Formspree:</strong> The contact form on this website uses Formspree to deliver messages. Formspree processes your email privately. I do not retain, sell, or access your submitted data beyond responding to your message.</p>
        <p><strong>Directus CMS:</strong> This website uses Directus as a headless CMS to manage content. The CMS is self-hosted and does not collect visitor data.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Children's Privacy</h2>
        <p>Null Comma products do not knowingly collect any personal information from children under 13. Our products do not include features that require age verification or account creation.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Data Retention</h2>
        <p>Since no personal data is collected, there is no data retention policy. Any data stored locally by our products (save files, preferences) remains on your device and is under your control at all times.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Changes to This Policy</h2>
        <p>This Privacy Policy may be updated at any time. Changes will be reflected on this page with an updated "Last updated" date. Continued use of any Null Comma product after changes constitutes acceptance of the updated policy.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Contact</h2>
        <p>Email: <a href="mailto:contact@nullcomma.com">contact@nullcomma.com</a></p>

        <p style={{ color: 'var(--color-grey)', fontSize: '0.85rem', marginTop: '2rem' }}>Last updated: May 2026</p>
      </div>
    </div>
  );
}

export default PrivacyPage;
