import { Link } from 'react-router-dom';

function PrivacyPage() {
  return (
    <div className="page-content fade-in" style={{ maxWidth: '720px', margin: '0 auto' }}>
      <Link to="/" className="button-back">&larr; Back</Link>

      <div className="glass-content-card">
        <h1 style={{ color: 'var(--color-light)', fontSize: '2rem', marginBottom: '0.5rem' }}>Privacy Policy</h1>
        <p style={{ color: 'var(--color-grey)', marginBottom: '1.5rem' }}>This policy applies to all Null Comma products: this website, games, tools, applications, and any services or integrations provided under the Null Comma brand.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Scope</h2>
        <p>This Privacy Policy covers all digital products and services created and distributed by Null Comma, including but not limited to: the nullcomma.com website, downloadable games and prototypes, the Null Comma Launcher, web applications, browser extensions, and any future tools or applications released under this brand.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>LGPD Compliance</h2>
        <p>Null Comma complies with the Brazilian General Data Protection Law (Lei Geral de Proteção de Dados — LGPD, Law No. 13.709/2018). All data processing activities described in this policy are conducted in accordance with LGPD principles, including purpose limitation, data minimization, transparency, and security. You have the right to access, correct, delete, or port any personal data we may process. For any data-related requests, contact us at <a href="mailto:contact@nullcomma.com">contact@nullcomma.com</a>.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Data Collection</h2>
        <p>Null Comma products are designed to minimize data collection. Most products do not collect, store, or share any personal data. However, some games and applications may use anonymous analytics for quality assurance and bug reporting purposes. This data is aggregated, does not identify individuals, and is used solely to improve product stability and user experience.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Website</h2>
        <p>The nullcomma.com website does not use cookies, tracking scripts, analytics services, or OAuth logins. No personal data is collected through browsing or interacting with the site. The contact form sends your message through <a href="https://formspree.io">Formspree</a>, which processes it privately. I do not retain, sell, or access your submitted data beyond responding to your message.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Games and Applications</h2>
        <p>Most games, tools, and applications created by Null Comma run locally on your device and do not transmit any data to external servers. Any data generated by these products (such as save files, preferences, or configuration) is stored exclusively on your local device.</p>
        <p>Some products may include optional anonymous analytics for quality assurance and bug reporting. This analytics data is aggregated and does not contain personally identifiable information such as your name, email, or device identifiers. It is used solely to identify crashes, performance issues, and usage patterns that help improve the product. Analytics can typically be disabled in the application's settings.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Authentication (OAuth)</h2>
        <p>Some Null Comma applications may use OAuth or similar authentication methods to allow you to sign in using third-party accounts (such as Google, Steam, or other providers). When you authenticate via OAuth:</p>
        <ul style={{ color: 'var(--color-light)', paddingLeft: '1.5rem', marginBottom: '1rem' }}>
          <li>Null Comma does not receive or store your password.</li>
          <li>Only the minimum necessary profile information is accessed (such as your display name and email) as permitted by the provider.</li>
          <li>Authentication tokens are stored securely on your device and can be revoked at any time through the provider's settings.</li>
          <li>We do not share your authentication data with any third parties.</li>
        </ul>
        <p>Specific details about what data is collected through OAuth are provided within each application that uses authentication.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Third-Party Services and Integrations</h2>
        <p>Some Null Comma products may interact with third-party services:</p>
        <p><strong>Steam:</strong> Games distributed on Steam may use the Steamworks SDK for features such as achievements, cloud saves, and leaderboards. These features are governed by Valve's privacy policy. Null Comma does not access or store any Steam user data.</p>
        <p><strong>YouTube:</strong> This website embeds video trailers from YouTube. YouTube has its own privacy policy. This site is not affiliated with YouTube or Google.</p>
        <p><strong>Formspree:</strong> The contact form on this website uses Formspree to deliver messages. Formspree processes your email privately. I do not retain, sell, or access your submitted data beyond responding to your message.</p>
        <p><strong>Directus CMS:</strong> This website uses Directus as a headless CMS to manage content. The CMS is self-hosted and does not collect visitor data.</p>
        <p><strong>Analytics Providers:</strong> When anonymous analytics are used in games or applications, they may be processed through third-party analytics services. These services are selected based on their privacy practices and commitment to data anonymization.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Children's Privacy</h2>
        <p>Null Comma products do not knowingly collect any personal information from children under 13. Our products do not include features that require age verification or account creation, except where OAuth authentication is used — in which case the third-party provider's age restrictions apply.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Data Retention</h2>
        <p>Any data stored locally by our products (save files, preferences, configuration) remains on your device and is under your control at all times. Authentication tokens are stored securely and can be revoked through the provider. Anonymous analytics data is retained only as long as necessary for quality assurance purposes and is processed in aggregated form.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Your Rights Under LGPD</h2>
        <p>Under the Brazilian LGPD, you have the following rights regarding your personal data:</p>
        <ul style={{ color: 'var(--color-light)', paddingLeft: '1.5rem', marginBottom: '1rem' }}>
          <li><strong>Access:</strong> Request confirmation of whether we process your data and access what is stored.</li>
          <li><strong>Correction:</strong> Request correction of incomplete, inaccurate, or outdated data.</li>
          <li><strong>Deletion:</strong> Request deletion of personal data processed with your consent.</li>
          <li><strong>Portability:</strong> Request transfer of your data to another service provider.</li>
          <li><strong>Revocation:</strong> Revoke consent for data processing at any time.</li>
        </ul>
        <p>To exercise any of these rights, contact us at <a href="mailto:contact@nullcomma.com">contact@nullcomma.com</a>.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Changes to This Policy</h2>
        <p>This Privacy Policy may be updated at any time. Changes will be reflected on this page with an updated "Last updated" date. Continued use of any Null Comma product after changes constitutes acceptance of the updated policy.</p>

        <h2 style={{ color: 'var(--color-purple)', fontSize: '1.3rem', marginTop: '2rem', marginBottom: '0.75rem' }}>Contact</h2>
        <p>Email: <a href="mailto:contact@nullcomma.com">contact@nullcomma.com</a></p>

        <p style={{ color: 'var(--color-grey)', fontSize: '0.85rem', marginTop: '2rem' }}>Last updated: May 2026</p>
      </div>
    </div>
  );
}

export default PrivacyPage;
